name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t simple-webapp:latest ./app

      - name: Push to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push simple-webapp:latest

      - name: Deploy to AWS (EC2)
        run: |
          # Assuming you have a script for deploying to EC2
          chmod +x ./deploy/deploy_to_ec2.sh
          ./deploy/deploy_to_ec2.sh
